### ISSUE TITLE
Map projection

### ISSUE THREAD

**Issue by bbakernoaa** [dtonggmu/haqast#3]
@dtonggmu 

Looked into the projection.  We are using he Lambert Equal Area projection.  We can simply change the projection in the plotting script to use Lamber Conformal Conic.  simply by changing the line:

```python
m = Basemap(projection='laea', resolution='h', lat_1=lat1, lat_2=lat2, lat_0=lat0, lon_0=lon0, lon_1=lon1,
```

to 

```python
m = Basemap(projection='lcc', resolution='h', lat_1=lat1, lat_2=lat2, lat_0=lat0, lon_0=lon0, lon_1=lon1,
```

This will give a plot something like this 
![test](https://cloud.githubusercontent.com/assets/22104759/21686456/7fba1760-d333-11e6-96c9-8cb57f165de8.jpg)

**Comment by semylab** [comment]
I applied the code. Now, the updated version is working. A plot image replacing by new one in Reanalysis menu is also finished.

Thanks!
